---
title: "Data 607 - Final Project - Proposal"
author: "Glen Dale Davis"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## One Paragraph That:

### Includes Your Motivation:

*Proposal describes your motivation for performing this analysis.*

We would like to help a birdwatcher in New York plan a plane trip across the entire United States (US) that prioritizes seeing a new bird in every state he visits. If he has the opportunity to see a new bird in a state where that bird is the state bird, that always takes precedence. What is the lowest weighted path he can take if each state is a vertex he can visit only once, and the edges between the state he is in and any state he hasn't visited yet are assigned weights equal to the inverse probability of seeing a new bird by traveling there? (We are using the inverse probability so that lower weights are assigned to new birds with higher chances of being seen, and paths to those birds are then considered better than paths to new birds with lower chances of being seen. We haven't quite figured out the state bird priority modifier yet.) [Bird Buddy](https://live.mybirdbuddy.com/) sells fancy bird feeders equipped with cameras that take photos of birds as they feed and identify the species. They release anonymized geospatial data monthly that includes the time each photo was taken and the species that was captured on camera. We have aggregated this data and mapped the longitude and latitude coordinates to states, and we have calculated the probability of seeing species in each state based on the number of times that species has been seen in that state since October 2022, the first month Bird Buddy released data for. We have removed geospatial data that falls outside the US and the District of Columbia (DC), and we have removed species with probabilities of being seen of less than 0.001 from our analysis. We have extracted the [list of US/DC state birds from Wikipedia](https://en.wikipedia.org/wiki/List_of_U.S._state_birds). Now we are ready to find the Hamiltonian path (in which every state is a vertex to be visited once and only once) that solves our problem. For the sake of simplicity, the edge weights will be based on a single bird for each so-far unvisited state: the most likely bird to be seen in that state, excepting any already seen birds from previously visited states. So we will have to keep track of which birds we've seen as we construct the path so that we update the edge weights after each step. We will also keep track of each bird we have seen's probability of being seen for the next step of our analysis. Once we have our Hamiltonian path, we will then let it play out, so to speak. This will require setting up a transition matrix for moving along the markov chain that represents our path. The last state in the path will be the absorbing state, and we will calculate the number of steps (which we can pretend are days) it should take us to get to the end by treating the birds' probabilities of being seen as our transition probabilities. While this analysis won't represent a realistic trip for most birdwatchers, it should be an entertaining exploration of graph theory with priorities. We will include a bonus breakdown of the states where you're least likely to see your state bird, as well as some suggestions for the many states that share a state bird and could perhaps make better choices.

### Includes Your Data Sources:

*Proposal describes likely data sources.*

[Bird Buddy](https://live.mybirdbuddy.com/)

[List of US State Birds](https://en.wikipedia.org/wiki/List_of_U.S._state_birds)

## An Approval Meeting Will Follow Where:

*You'll have to describe:*

* The reason (benefit) for doing this work and/or question you’re seeking to answer

* Where you’ll source the data

* The overall flow
